Updated archiso hook. Added archisolabel boot option back in. This is a way to boot the livecd based on format label. But you don't have to use it.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/archiso/mkinitcpio/initcpio/hooks/archiso b/archiso/mkinitcpio/initcpio/hooks/archiso
--- a/archiso/mkinitcpio/initcpio/hooks/archiso
+++ b/archiso/mkinitcpio/initcpio/hooks/archiso
@@ -59,6 +59,29 @@ _mnt_squashfs() {
     #fi
 }
 
+_find_label() {
+
+    FSTYPE=$(blkid -o value -s TYPE -p ${archisodevice} 2> /dev/null)
+    if [ -n "${FSTYPE}" ]; then
+        if mount -r -t "${FSTYPE}" ${archisodevice} /bootmnt > /dev/null 2>&1; then
+            if [ -e "/bootmnt/${cdname}/${sgnfile}" ]; then
+                echo "SUCCESS: Mounted archiso volume successfully."
+                BOOT_MOUNT=/bootmnt
+                found="1"
+            else
+                echo "ERROR: Mounting was successful, but the /bootmnt/${cdname}/${sgnfile} file does not exist."
+                found="0"
+            fi
+        else
+            echo "ERROR; Failed to mount ${archisodevice} (FS is ${FSTYPE})"
+            found="0"
+        fi
+    else
+        echo "ERROR: ${archisodevice} found, but the filesystem type is unknown."
+        found="0"
+    fi
+}
+
 _find_device() {
     msg "Scanning drives: "
     for device in /dev/hd[a-z] /dev/sr[0-9]* /dev/scd[a-z] /dev/sd[a-z][0-9] /dev/sg[0-9]*; do
@@ -159,6 +182,12 @@ run_hook () {
         sgnfile="livecd.sgn"
     fi
 
+    if [ "x${archisolabel}" != "x" ]; then
+        if [ "x${archisodevice}" = "x" ]; then
+            archisodevice="/dev/disk/by-label/${archisolabel}"
+        fi
+    fi
+
     # set mount handler for archiso
     mount_handler="archiso_mount_handler"
 }
@@ -180,7 +209,19 @@ archiso_mount_handler() {
     modprobe -q loop max_loop=255 >/dev/null 2>&1
     modprobe -q isofs >/dev/null 2>&1
     modprobe -q ext4 >/dev/null 2>&1
-    _find_device
+
+    if [ "x${archisodevice}" != "x" ]; then
+        #msg ":: Waiting for boot device..."
+        #while ! poll_device ${archisodevice} 30; do
+        #    echo "ERROR: boot device didn't show up after 30 seconds..."
+        #    echo "   Falling back to interactive prompt"
+        #    echo "   You can try to fix the problem manually, log out when you are finished"
+        #    launch_interactive_shell
+        #done
+        _find_label
+    else
+        _find_device
+    fi
 
     if [ "${found}" = "0" ]; then
         echo "   Falling back to interactive prompt"
