Updated mkarchiso script and isolinux.cfg file. Now it adds the CDNAME variable as a boot option since it could be change from default.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/archiso/mkarchiso b/archiso/mkarchiso
--- a/archiso/mkarchiso
+++ b/archiso/mkarchiso
@@ -523,6 +523,11 @@ _imgcommon () {
             exit 1
         fi
     fi
+
+    if ! sed "s|cdname=[^ ]*|cdname=${CDNAME}|" -i ${iso_dir}/boot/isolinux/isolinux.cfg; then
+        error "Error: ${iso_dir}/boot/isolinux/isolinux.cfg, doesn't exist.aborting."
+        exit 1
+    fi
 }
 
 command_iso () {
