Updated mkarchiso script. Updated archiso hooks. Added (I think) full support of linux-live scripts into archlinux initramfs.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/archiso/mkinitcpio/initcpio/linuxrc b/archiso/mkinitcpio/initcpio/linuxrc
--- a/archiso/mkinitcpio/initcpio/linuxrc
+++ b/archiso/mkinitcpio/initcpio/linuxrc
@@ -1,15 +1,15 @@
-_setup()
-{
+#!/bin/ash
+# Initial script for Linux Live operating system
+# Author: Tomas M <http://www.linux-live.org/>
+
 export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin
 
-mount -n -t proc proc /proc
-mount -n -t sysfs sysfs /sys
-mount -n -o remount,rw /         # for the case we forgot rw boot option
+#mount -n -t proc proc /proc
+#mount -n -t sysfs sysfs /sys
+#mount -n -o remount,rw /         # for the case we forgot rw boot option
 ln -sf /proc/mounts /etc/mtab    # this allows us to use umount -a
 
-. liblinuxlive
-
-header "starting Linux Live scripts <http://www.linux-live.org/>"
+. liblinuxlive # it requires proc to be mounted
 
 # Don't print kernel messages to konsole now.
 # Syslog will reset printk settings, no need to remember it here anymore.
@@ -18,10 +18,13 @@ echo "0" >/proc/sys/kernel/printk
 # Load essential drivers, like CDROM drivers, aufs/squashfs etc,
 # use mdev to create /dev/ devices and setup it as a hotplug-handler
 modprobe_essential_modules
-mdev_start_hotplug
 
-# /usr is compressed in initrd so it must be mounted from /usr.lzm
+# /usr and some drivers are compressed in initrd 
+# so it must be mounted from .lzm files
 #mount_initrd_loops
+
+# start hotplugging before hw drivers load
+mdev_start_hotplug
 
 # Then load drivers for data storage and input devices
 modprobe_usb_modules
@@ -31,7 +34,7 @@ debug_shell
 
 # make sure ext3 partitions are not mounted using ext2 driver,
 # and vfat partitions are not mounted using msdos driver
-echo -e "ext3\next2\nvfat\n*" >/etc/filesystems
+echo -e "ext4\next3\next2\nbtrfs\nvfat\n*" >/etc/filesystems
 
 mkdir -p $UNION
 mkdir -p $MEMORY
@@ -41,23 +44,37 @@ debug_shell
 # Find livecd data directory by searching for livecd.sgn file
 SGN=$(cmdline_value sgnfile)
 if [ "$SGN" = "" ]; then SGN=livecd.sgn; fi
-echolog "looking for data directory (searching for $SGN file)"
-
-mount -t tmpfs -o "size=1M" tmpfs $MOUNTDIR
+echolog "looking for '$LIVECDNAME' data directory (searching for $SGN file)"
 
 # First, try from= boot argument, if given
 DATAFROM=$(cmdline_value from)
 
+# If ip= parameter is present, assume we're booted over PXE
+# In that case, we have to initialize network very soon (now)
+# ip=<client-ip>:<boot-server-ip>:<gw-ip>:<netmask>
+# Nevertheless, from= parameter won't be overwritten by this
+IP=$(cmdline_value ip)
+if [ "$IP" != "" -a "$DATAFROM" = "" ]; then
+   DATAFROM="http://"$(echo $IP | cut -d : -f 2)
+fi
+
 if [ "$DATAFROM" ]; then
-   DATAFROM=$(find_in_computer $DATAFROM)
-   if [ "$DATAFROM" ]; then
-      mount_device $DATAFROM $LOOPMOUNT # mount again, it may be loop device
-      if [ $? -eq 0 -a "$(find_modules $LOOPMOUNT/$LIVECDNAME)" != "" ]; then
-         echolog "found in $DATAFROM"
-         DATA=$LOOPMOUNT/$LIVECDNAME
-      else
-         fumount $LOOPMOUNT
-	 fumount $MOUNTDIR/*
+   if [ "$(echo $DATAFROM | cut -b 1-7 | tr "[:upper:]" "[:lower:]")" = "http://" ]; then
+      init_dhcp $(modprobe_network_modules)
+      mount_httpfs $DATAFROM $MOUNTDIR/httpfs
+      # if mountdir/httpfs/livecdname is found, set DATA=, else umount httpfs
+      # - currently this part works even without the above mentioned, but livecd.sgn is required now untill it's uncommented
+   else
+      DATAFROM=$(find_in_computer $DATAFROM)
+      if [ "$DATAFROM" ]; then
+         mount_device $DATAFROM $LOOPMOUNT # mount again, it may be loop device
+         if [ $? -eq 0 -a "$(find_modules $LOOPMOUNT/$LIVECDNAME)" != "" ]; then
+            echolog "found in $DATAFROM"
+            DATA=$LOOPMOUNT/$LIVECDNAME
+         else
+            fumount $LOOPMOUNT
+            fumount $MOUNTDIR/*
+         fi
       fi
    fi
 fi
@@ -75,11 +92,11 @@ Workaround: Copy the directory $LIVECDNAME from your boot device to an IDE/SATA
 disk, eg. to /mnt/hda1/$LIVECDNAME or C:\\$LIVECDNAME. Then try to boot again."
 fi
 
-echolog "using $LIVECDNAME data from $DATA"
+echolog "Using $LIVECDNAME data from $DATA"
 
 debug_shell
 
-echolog "setting up directory for changes"
+echolog "Setting up directory for changes ..."
 CHANGESVAL=$(cmdline_value changes)
 
 if [ "$CHANGESVAL" ]; then
@@ -98,7 +115,7 @@ rm -f $MEMORY/empty 2>/dev/null
 # if changes can't be mounted or the filesystem is not writable,
 # fallback to the default: tmpfs
 if [ $? -ne 0 ]; then
-   echolog "changes not used or not writable, using memory only"
+   echolog "Changes not used or not writable, using memory only"
    fumount $MEMORY
    mkdir -p $MEMORY # mount_device might removed it
 
@@ -110,7 +127,7 @@ else
    # So it is writable, we will keep the filesystem mounted.
    # Check if it supports links and chmod.
    # If not, overmount CHANGES using posixovl
-   echolog "testing the filesystem for posix compatibility"
+   echolog "Testing the filesystem for posix compatibility ..."
    touch $MEMORY/.empty1 && \
    ln -sf $MEMORY/.empty1 $MEMORY/.empty2 2>/dev/null && \
    chmod +x $MEMORY/.empty1 2>/dev/null  && \
@@ -120,15 +137,16 @@ else
    rm $MEMORY/.empty1 $MEMORY/.empty2 2>/dev/null
 
    if [ $? -ne 0 ]; then
-      echolog "not compatible - starting posixovl"
+      echolog "Not compatible - starting posixovl"
       rm $MEMORY/.empty1 $MEMORY/.empty2 2>/dev/null
       mkdir -p $CHANGES
-      posixovl -F $CHANGES
+      posixovl -F $CHANGES -- -o attr_timeout=300,entry_timeout=300,negative_timeout=300,kernel_cache,allow_other
+      find $CHANGES >/dev/null 2>&1 # cache everything now
    fi
 fi
 
 # $UNION will be used as a root directory, livecd modules will be added soon
-echolog "setup union directory (using aufs)"
+echolog "Setup union directory (using aufs)"
 
 mkdir -p $CHANGES
 mkdir -p $IMAGES
@@ -139,7 +157,6 @@ debug_shell
 if [ "$XINO" != "$MEMORY" ]; then
    mkdir -p $XINO
    mount -n -t tmpfs tmpfs $XINO
-   mount -n -t tmpfs tmpfs $IMAGES
 fi
 
 # mount aufs using the writable branch as the first one (leftmost/topmost)
@@ -152,7 +169,7 @@ debug_shell
 # (skip modules from /optional/ which are not listed in load= boot option)
 # Finaly modify DATA variable so it will point to correct directory
 if [ "$(cmdline_parameter toram)" != "" -o "$(cmdline_parameter copy2ram)" != "" ]; then
-   echolog "copying data to RAM, this may take some time..."
+   echolog "copying $LIVECDNAME data to RAM, this may take some time..."
    mkdir -p $COPY2RAM
 
    # make sure it's in RAM even with changes= parameter
@@ -172,14 +189,16 @@ debug_shell
 MODPATH=$(cmdline_value modpath)
 if [ "$MODPATH" != "" ]; then
 	MODPATH=$(find_in_computer $MODPATH)
-	mount -n -o rbind $MODPATH $(dirname $DATA)/$LIVECDNAME/tmp 2>/dev/null
+	if [ $(cmdline_value findiso) ]; then
+		mount_device $MODPATH $FINDISO/$LIVECDNAME/tmp rbind
+	else
+		mount_device $MODPATH $DATA/tmp rbind
+	fi
 fi
-
-
 
 # DATA contains path to the base directory of all fs modules which need
 # to be mounted and inserted into live filesystem. Do it now.
-echolog "inserting all modules and creating live filesystem"
+echolog "Loading modules:"
 union_insert_modules $UNION $DATA $IMAGES
 
 # the $MEMORY directory can contain $MEMORY/modules too
@@ -188,26 +207,40 @@ union_insert_modules $UNION $MEMORY $IMAGES
 
 debug_shell
 
-if [ "$(cmdline_parameter norootcopy)" ]; then 
-echolog "no copying of rootcopy directory"
+ROOTCOPY=$(cmdline_value rootcopy)
+if [ $(cmdline_parameter norootcopy) ]; then
+	echolog "Not using rootcopy"
+elif [ "$ROOTCOPY" ]; then
+	echolog "Mounting content of rootcopy directory"
+	ROOTCOPY=$(find_in_computer $ROOTCOPY)
+    mount_device $ROOTCOPY $DATA/rootcopy rbind
+    echolog "Copying content of rootcopy directory"
+	cp -af $DATA/rootcopy/* $UNION 2>/dev/null # may be empty
 else
-echolog "copying content of rootcopy directory"
-cp -af $DATA/rootcopy/* $UNION 2>/dev/null # may be empty
+	echolog "Copying content of rootcopy directory"
+	cp -af $DATA/rootcopy/* $UNION 2>/dev/null # may be empty
 fi
 
-echolog "copying liblinuxlive library to union"
+# TODO: if copy2ram is used, there is no need to preserve the original in memory anymore
+#if [ "$DATA" = "$COPY2RAM" ]; then 
+#    rm from memory once ??
+#fi
+
+echolog "Copying liblinuxlive library to union"
 cp -af /liblinuxlive $UNION/usr/lib/
 
 debug_shell
 
-echolog "creating /etc/fstab"
+echolog "Recreating /etc/fstab and /mnt directories"
 touch $UNION/etc/fstab
+rmdir $UNION/mnt/* 2>/dev/null
 fstab_update $UNION
+#fstab_clean $UNION
 
 # everything is ready now, so we may unload unused kernel modules
 # and do some cleanup, unmount few things which are no longer needed.
-rmmod_unused_modules
-fumount /usr
+#rmmod_unused_modules
+#fumount /usr
 fumount /sys
 
 # More likely these directories aren't there.
@@ -221,7 +254,15 @@ chmod 1777 $UNION/tmp
 
 # Boot will contain whatever was in ./boot directory in the bootable media
 # Error output goes to null, as nothing is mounted with copy2ram
-mount -n -o rbind $(dirname $DATA)/boot $UNION/boot 2>/dev/null
+#mount -n -o rbind $(dirname $DATA)/boot $UNION/boot 2>/dev/null
+
+debug_shell
+
+echolog "move memory folder to union"
+mkdir -p $UNION/$INITRAMDISK/$MEMORY
+mkdir -p $UNION/$INITRAMDISK/$MOUNTDIR
+mount -n -o move $MEMORY $UNION/$INITRAMDISK/$MEMORY
+mount -n -o move $MOUNTDIR $UNION/$INITRAMDISK/$MOUNTDIR
 
 debug_shell
 
@@ -239,9 +280,6 @@ mkdir -p $INITRAMDISK
 if [ ! -e /dev/console ]; then mknod /dev/console c 5 1; fi
 cp -fdR /dev . 2>/dev/null
 
-# Look to see if the user requested a specific runlevel
-runlevel=$(cmdline_runlevel)
-
 # find chroot and init
 if [ -x bin/chroot ]; then  CHROOT=bin/chroot; fi
 if [ -x sbin/chroot ]; then  CHROOT=sbin/chroot; fi
@@ -255,33 +293,20 @@ if [ "$INIT" = "" ]; then fatal "Can't find executable init command"; fi
 
 # time to end Linux Live scripts and start the distribution itself,
 # using /sbin/init or whatever was found.
-header "linux live end, starting the Linux distribution"
 
 debug_shell
 
-mkdir -p /union/mnt/live/memory
-mkdir -p /union/mnt/live/mnt
-mount -n -o move /memory /union/mnt/live/memory 2>/dev/null
-mount -n -o move /mnt /union/mnt/live/mnt
-
-
-#if [ -e "$DATA/$SGN" ]; then
-#	mount -n -o rbind $(dirname $DATA) /union/mnt/live/mnt/bootmnt
-#	mount -n -o rbind /union/mnt/live/mnt/bootmnt/$LIVECDNAME
-#	mount -n -o rbind /union/boot /union/mnt/live/mnt/bootmnt/boot
-#elif [ $DATAFROM ]; then
-#	mount -n -o bind 
-#else
-#	echo "Failed to mount $DATA in /union/mnt/live/mnt"
-#fi
-
-cp -Raf /bin /union/mnt/live
-ln -sf bin /union/mnt/live/sbin
-cp -Raf /etc /union/mnt/live
-cp -Raf /var /union/mnt/live
-cp -af /init /union/mnt/live
-cp -af /cleanup /union/mnt/live
-cp -af /liblinuxlive /union/mnt/live
+echolog "Killing udevd"
+#Special handling if udev is running
+udevpid=$(/bin/pidof udevd)
+if [ -n "${udevpid}" ]; then
+    # Settle pending uevents, then kill udev
+    /sbin/udevadm settle
+    /bin/kill ${udevpid} > /dev/null 2>&1
+    while /bin/pidof udevd >/dev/null; do
+        sleep 0.1
+    done
+fi
 
 debug_shell
 
@@ -291,20 +316,14 @@ mount -n -o remount,ro aufs .
 # This allows us to use the cleanup script during reboot, as init will be
 # started from memory and not from the union and /union will not be busy.
 
-cp -af $INIT /bin
+cp -af $INIT $INITRAMDISK/$MEMORY
 if [ $? -eq 0 ]; then
    #pivot_root . $INITRAMDISK
-   #exec $CHROOT . $INITRAMDISK/bin/init $runlevel <dev/console >dev/console 2>&1
-#else # If copying fails, start init directly.
+   exec $CHROOT . $INITRAMDISK/$MEMORY/init <dev/console >dev/console 2>&1
+else # If copying fails, start init directly.
    #pivot_root . $INITRAMDISK
-   exec $CHROOT . $INIT $runlevel <dev/console >dev/console 2>&1
+   exec $CHROOT . $INIT <dev/console >dev/console 2>&1
 fi
 
 header "!!ERROR!!"
 fatal "You are not supposed to be here, something went wrong!"
-}
-
-run_hook()
-{
- _setup
-}
